// Shared mock data for Denoisr — used across canvas, mobile and web artboards.

window.DENOISR_JOBS = [
  {
    id: 'j1',
    company: 'Northwind Mobility',
    initials: 'NM',
    role: 'Senior Product Designer',
    pitch: 'Reimagine how 40M commuters plan a multi-modal trip.',
    location: 'Berlin, Remote-friendly',
    years: '5+ years',
    comp: '€95–120k',
    type: 'Full-time',
    mode: 'Hybrid',
    tags: ['Mobility', 'Series B', 'Design Systems'],
    solve: ['Lead the routing-and-payments surface end-to-end', 'Push our visual system into a mature 2.0', 'Mentor two mid-level designers'],
    why: 'A founder who designs — and ships — alongside you.',
    swatch: 'oklch(0.78 0.10 220)',
  },
  {
    id: 'j2',
    company: 'Quay Labs',
    initials: 'QL',
    role: 'Founding ML Engineer',
    pitch: 'Inference for legal teams. Real cases, not chatbots.',
    location: 'New York, On-site',
    years: '4+ years',
    comp: '$180–220k + equity',
    type: 'Founding',
    mode: 'On-site',
    tags: ['LLMs', 'Legal-tech', 'Seed'],
    solve: ['Stand up retrieval over 90M court filings', 'Own evals, latency budgets and red-teaming', 'Sit between two former federal litigators'],
    why: 'You will own the inference layer from day one.',
    swatch: 'oklch(0.80 0.11 65)',
  },
  {
    id: 'j3',
    company: 'Solace Health',
    initials: 'SH',
    role: 'Staff iOS Engineer',
    pitch: 'Build the chronic-care companion 1M patients open daily.',
    location: 'Remote (US/EU)',
    years: '7+ years',
    comp: '$200–240k',
    type: 'Full-time',
    mode: 'Remote',
    tags: ['Health', 'Series C', 'Swift / SwiftUI'],
    solve: ['Architect offline-first sync', 'Set the bar for HIG-native craft', 'Coach an iOS guild of nine'],
    why: 'Healthcare with the polish of consumer software.',
    swatch: 'oklch(0.82 0.08 150)',
  },
  {
    id: 'j4',
    company: 'Atlas Foundry',
    initials: 'AF',
    role: 'Brand & Editorial Lead',
    pitch: 'Set the visual voice for a new kind of climate fund.',
    location: 'London, Hybrid',
    years: '6+ years',
    comp: '£80–105k',
    type: 'Full-time',
    mode: 'Hybrid',
    tags: ['Climate', 'Brand', 'Editorial'],
    solve: ['Steward identity across film, print and product', 'Hire and lead an in-house studio of four', 'Partner directly with the GP team'],
    why: 'Editorial craft, with budget to commission the best.',
    swatch: 'oklch(0.80 0.08 30)',
  },
];

window.DENOISR_PEOPLE = [
  {
    id: 'p1',
    name: 'Ines Okafor',
    initials: 'IO',
    headline: 'Founding designer · ex-Linear, ex-Stripe',
    location: 'Lisbon · open to remote',
    looking: 'Co-founder',
    why: 'Looking for a technical co-founder. Building something in writing tools.',
    overlap: ['Worked with Maya R.', 'Both ex-Stripe', 'Both wrote at A List Apart'],
    tags: ['Design', '0→1', 'Consumer'],
    swatch: 'oklch(0.78 0.10 320)',
    age: '32',
  },
  {
    id: 'p2',
    name: 'Daniel Sato',
    initials: 'DS',
    headline: 'Staff engineer · distributed systems',
    location: 'Tokyo · willing to travel',
    looking: 'Peer network',
    why: 'I write a small newsletter on databases. Coffee chats welcome — especially with anyone running Cassandra at scale.',
    overlap: ['Both at QCon Tokyo 2024', '2 mutuals at Stripe'],
    tags: ['Backend', 'Databases', 'Mentor'],
    swatch: 'oklch(0.80 0.09 200)',
    age: '38',
  },
  {
    id: 'p3',
    name: 'Priya Raman',
    initials: 'PR',
    headline: 'Recruiter · senior eng, ex-FAANG roles',
    location: 'Bengaluru · global remit',
    looking: 'Candidates',
    why: 'Quietly placing senior backend folks at three Series-B teams. Happy to share the rubric before you decide.',
    overlap: ['Mentored Aarti S.', '5 mutuals'],
    tags: ['Recruiter', 'Senior eng', 'Series B'],
    swatch: 'oklch(0.80 0.08 90)',
    age: '34',
  },
  {
    id: 'p4',
    name: 'Marcus Vale',
    initials: 'MV',
    headline: 'Product manager · fintech infra',
    location: 'NYC · in person preferred',
    looking: 'Coffee chats',
    why: 'New to NY. Would love to meet anyone shipping in payments, treasury or B2B finance — buying coffee for two months.',
    overlap: ['Both at Stripe Sessions', 'Read same Substack'],
    tags: ['PM', 'Payments', 'B2B'],
    swatch: 'oklch(0.78 0.10 250)',
    age: '29',
  },
];
